---
title: "Conference Events"
author: "Shareen Chang"
date: "5/8/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(ggplot2)
library(plotly)
conf_events <- read.csv("data/events.csv", stringsAsFactors = F)
```

## Building a conference events graph

In this text, I explore making a graph about things that happened to me at
a conference. Those things include:
```{r cars, echo = FALSE}
kable(conf_events)
```

## Starting to make some plots

First try:

```{r pressure, echo=FALSE}
basic_plot <- ggplot(data = conf_events)
basic_plot
```

```{r}
scale_x <- scale_x_continuous(
  name = "",
  limits = c(0, 1),
  breaks = 0.5,
  labels = "Truly Excruciating",
  sec.axis = dup_axis(labels = "Genuinely Awesome")
)

scale_y <- scale_y_continuous(
  name = "",
  limits = c(0, 1),
  breaks = 0.5,
  labels = "Industry",
  sec.axis = dup_axis(labels = "Academic")
)

final_chart <- basic_plot + 
  geom_point(mapping = aes(x = category, y = scenario, text = label)) +
  geom_vline(xintercept = 0.5) +
  geom_hline(yintercept = 0.5) +
  scale_y +
  scale_x

ggplotly(final_chart, tooltip = "text")
```


